In [1]:
import prestodb
import pandas as pd
conn=prestodb.dbapi.connect(
    host='localhost',
    port=9000,
    user='python',
    catalog='hive',
    schema='default',
)
cur = conn.cursor()

def fetch_query_to_dataframe(cur, query):
    cur.execute(query)
    rows = cur.fetchall()
    columns = list(map(lambda x: x[0], cur.description))
    return pd.DataFrame(rows, columns = columns)

In [3]:
partition = '2021_01'
zone_query = f"""
    with latest_tims as (SELECT messagebody, sourcedevice FROM smart_columbus_cve__captcha where messagetype = 'TIM' and

        cast(json_extract(messagebody,'$.dataFrames[0].content[1][0].item[1]') as integer) = 4124 and
        cast(json_extract(messagebody,'$.dataFrames[0].content[1][1].item[1]') as integer) = 12564 and
        cast(json_extract(messagebody,'$.dataFrames[0].content[1][2].item[1]') as integer) = 8720 and
        os_partition = '{partition}'
        ),

        latest_tim_polygonPoints as (
            select 
                cast(json_extract(messagebody,'$.dataFrames[0].regions[0].anchor.lat') as double) / 10000000 as anchorLat,
                cast(json_extract(messagebody,'$.dataFrames[0].regions[0].anchor.long') as double) / 10000000 as anchorLon,
                cast(json_extract(messagebody,'$.dataFrames[0].regions[0].description[1].offset[1][1]') AS ARRAY<JSON>),

                transform(cast(json_extract(messagebody,'$.dataFrames[0].regions[0].description[1].offset[1][1]') AS ARRAY<JSON>), x->
                
                    cast(cast(JSON_EXTRACT_SCALAR(x, '$.delta[1].lon') as double) /10000000 as varchar) || ' ' || cast(cast(JSON_EXTRACT_SCALAR(x, '$.delta[1].lat') as double) /10000000 as varchar)
                )
                as polygonVerticies
                from latest_tims
        ),
        latest_tim_polygonWktStrings as (
        select *,
        'POLYGON ((' || array_join(polygonVerticies, ',') || ',' || element_at(polygonVerticies,1)  || '))' as wellKnownText
        from latest_tim_polygonPoints 
        ),
        distinctPolygonWktStrings as (
        select distinct anchorLat, anchorLon, wellKnownText from latest_tim_polygonWktStrings
        ),
        distinctPolygonWktGeometryObjects as (
        SELECT anchorLon, anchorLat, ST_GeometryFromText(wellKnownText) as schoolZoneGeometryObjects from distinctPolygonWktStrings
        ),

        all_tims as (SELECT messagebody FROM smart_columbus_cve__captcha where messagetype = 'TIM' and
        minute(from_iso8601_timestamp(timestamp)) = 0 and
        second(from_iso8601_timestamp(timestamp)) = 0 and
        cast(json_extract(messagebody,'$.dataFrames[0].content[1][0].item[1]') as integer) = 4124 and
        cast(json_extract(messagebody,'$.dataFrames[0].content[1][1].item[1]') as integer) = 12564 and
        cast(json_extract(messagebody,'$.dataFrames[0].content[1][2].item[1]') as integer) = 8720 and
        os_partition = '{partition}'
        ),
        schoolZoneTimes as (
            select distinct
                cast(json_extract(messagebody,'$.dataFrames[0].duratonTime') as bigInt) as durationTime,
                cast(json_extract(messagebody,'$.dataFrames[0].startTime') as bigInt) as startTime,
                cast(json_extract(messagebody,'$.dataFrames[0].regions[0].anchor.lat') as double) / 10000000 as anchorLat,
                cast(json_extract(messagebody,'$.dataFrames[0].regions[0].anchor.long') as double) / 10000000 as anchorLon
                
                from all_tims
        ),

        latest_bsm as (
        SELECT timestamp as bsmTimestamp,
        json_extract(messageBody,'$.coreData.id') as vehicleId,
        cast(json_extract(messageBody,'$.coreData.speed') as double) / 50 * 2.23694 as bsmSpeedMph,
        cast(json_extract(messageBody,'$.coreData.long') as double ) /10000000 as bsmLon,
        cast(json_extract(messageBody,'$.coreData.lat') as double ) /10000000 as bsmLat,
        cast(json_extract(messageBody,'$.coreData.heading') as double ) /80 as bsmHeading,
        24*60*(day_of_year(from_iso8601_timestamp(timestamp))-1) + 60*hour(from_iso8601_timestamp(timestamp)) + minute(from_iso8601_timestamp(timestamp)) as bsmMinuteOfTheYear
        FROM smart_columbus_cve__captcha where messageType = 'BSM' and (sourceDevice = 'high_dominion_cvcp' or sourceDevice = 'high_weisheimer_cvcp' or sourceDevice = 'high_northbroadway_cvcp' or sourceDevice = 'high_como_cvcp' or sourceDevice = 'cleveland_westerville_cvcp' or sourceDevice = 'cleveland_weber_cvcp') and
        os_partition = '{partition}'
        ),

        distinct_bsm as (
        select min(bsmTimestamp) as bsm_timestamp, min(bsmSpeedMph) as bsmSpeedMph, min(bsmHeading) as bsmHeading, min(bsmMinuteOfTheYear) as bsmMinuteOfTheYear, vehicleId, bsmLon, bsmLat
            from latest_bsm group by vehicleId, bsmLon, bsmLat
        ),
        distinct_bsm_geometryObjects as(
        SELECT *, ST_Point(bsmLon,bsmLat) as bsmPointGeometryObjects
        from distinct_bsm
        ),

        bsmInSchoolZone as (
        SELECT *
        FROM distinct_bsm_geometryObjects p, distinctPolygonWktGeometryObjects q 
        WHERE ST_Contains(q.schoolZoneGeometryObjects, p.bsmPointGeometryObjects)
        ),
        bsmInSchoolZone2 as (
        SELECT
        p.vehicleId as bsm_vehicleId, p.bsmHeading as bsm_heading, p.bsm_timestamp as bsm_timestamp, p.bsmMinuteOfTheYear as bsm_minuteOfYear, p.bsmLat as bsm_lat, p.bsmLon as bsm_long, p.bsmSpeedMph as bsm_speed,
        q.anchorLat as SZ_anchorLat, q.anchorLon as SZ_anchorLon, q.startTime as SZ_startMinuteOfYear, q.durationTime as SZ_durationMinutes, cast(if(bsmSpeedMph>20, true, false) as boolean) as warningIssued

        FROM bsmInSchoolZone p JOIN schoolZoneTimes q

        ON p.anchorLat = q.anchorLat and 
        p.anchorLon = q.anchorLon and 
        p.bsmMinuteOfTheYear > q.startTime and  
        p.bsmMinuteOfTheYear < q.startTime + q.durationTime
        )
        SELECT * from bsmInSchoolZone2
    """

df = fetch_query_to_dataframe(cur, zone_query)

In [4]:
df

,bsm_vehicleId,bsm_heading,bsm_timestamp,bsm_minuteOfYear,bsm_lat,bsm_long,bsm_speed,SZ_anchorLat,SZ_anchorLon,SZ_startMinuteOfYear,SZ_durationMinutes,warningIssued
0,147331962,2.8625,2021-01-28T12:45:32.892Z,39645,40.053621,-83.019982,15.658580,40.053569,-83.019987,39635,30,False
1,2743630331,2.7125,2021-01-28T12:47:31.742Z,39647,40.052399,-83.019983,0.000000,40.053569,-83.019987,39635,30,False
2,2066586121,182.6625,2021-01-28T12:40:35.656Z,39640,40.055461,-83.019953,19.371900,40.053569,-83.019987,39635,30,False
3,1345131051,182.4125,2021-01-28T12:51:15.995Z,39651,40.054639,-83.020005,21.250930,40.053569,-83.019987,39635,30,True
4,1345131051,182.2875,2021-01-28T12:51:19.880Z,39651,40.054307,-83.020023,19.819288,40.053569,-83.019987,39635,30,False
...,...,...,...,...,...,...,...,...,...,...,...,...
92019,1540029501,2.1375,2021-01-06T13:04:45.348Z,7984,40.052425,-83.019997,6.531865,40.053569,-83.019987,7955,30,False
92020,425026050,2.6250,2021-01-07T19:32:00.617Z,9812,40.053297,-83.019933,21.474624,40.053569,-83.019987,9805,30,True
92021,389907909,1.9625,2021-01-05T19:43:24.544Z,6943,40.053729,-83.019914,19.550856,40.053569,-83.019987,6925,30,False
92022,2828537162,2.0875,2021-01-05T12:41:35.982Z,6521,40.052892,-83.019989,5.950260,40.053569,-83.019987,6515,30,False
92023,389907909,2.4750,2021-01-05T19:43:33.391Z,6943,40.054265,-83.019883,10.379402,40.053569,-83.019987,6925,30,False

In [5]:
df.to_csv('school_zones.csv', index=False)