In [1]:
import prestodb
import pandas as pd
conn=prestodb.dbapi.connect(
    host='localhost',
    port=9000,
    user='python',
    catalog='hive',
    schema='default',
)
cur = conn.cursor()

def fetch_query_to_dataframe(cur, query):
    cur.execute(query)
    rows = cur.fetchall()
    columns = list(map(lambda x: x[0], cur.description))
    return pd.DataFrame(rows, columns = columns)

In [2]:
source_table = "cve_signal_messages"

In [3]:
srm_query = f"""
select * from {source_table} where os_partition = '2021_01' and messagetype = 'SRM'
"""

df = fetch_query_to_dataframe(cur, srm_query + " limit 10")

In [4]:
body = df['messagebody'][0]
body

'{"regional":null,"requestor":{"id":["entityID",889973489],"name":[85,110,107,110,111,119,110],"position":{"heading":0,"position":{"elevation":2360,"lat":400602113,"long":-829530181},"speed":{"speed":34,"transmisson":"unavailable"}},"routeName":[85,110,107,110,111,119,110],"transitStatus":[],"type":{"request":"requestImportanceLevelUnKnown","role":"transit","subrole":"requestSubRoleUnKnown"}},"requests":[{"duration":5000,"minute":41385,"request":{"id":{"id":3440},"inBoundLane":["lane",18],"outBoundLane":["lane",86],"requestID":76,"requestType":"priorityRequestUpdate"},"second":37000}],"second":0,"sequenceNumber":14,"timeStamp":null}'

In [5]:
import json

srm = json.loads(body)

print(json.dumps(srm, indent=2))

{
  "regional": null,
  "requestor": {
    "id": [
      "entityID",
      889973489
    ],
    "name": [
      85,
      110,
      107,
      110,
      111,
      119,
      110
    ],
    "position": {
      "heading": 0,
      "position": {
        "elevation": 2360,
        "lat": 400602113,
        "long": -829530181
      },
      "speed": {
        "speed": 34,
        "transmisson": "unavailable"
      }
    },
    "routeName": [
      85,
      110,
      107,
      110,
      111,
      119,
      110
    ],
    "transitStatus": [],
    "type": {
      "request": "requestImportanceLevelUnKnown",
      "role": "transit",
      "subrole": "requestSubRoleUnKnown"
    }
  },
  "requests": [
    {
      "duration": 5000,
      "minute": 41385,
      "request": {
        "id": {
          "id": 3440
        },
        "inBoundLane": [
          "lane",
          18
        ],
        "outBoundLane": [
          "lane",
          86
        ],
        "requestID": 76,
        "requestType": "priorityRequestUpdate"
      },
      "second": 37000
    }
  ],
  "second": 0,
  "sequenceNumber": 14,
  "timeStamp": null
}

In [6]:
ssm_query = f"""
select * from {source_table} where os_partition = '2021_01' and messagetype = 'SSM'
"""

df = fetch_query_to_dataframe(cur, ssm_query + " limit 10")
body = df['messagebody'][0]

ssm = json.loads(body)

print(json.dumps(ssm, indent=2))

{
  "regional": null,
  "second": 14130,
  "sequenceNumber": 1,
  "status": [
    {
      "id": {
        "id": 4036
      },
      "sequenceNumber": 1,
      "sigStatus": [
        {
          "inboundOn": [
            "lane",
            49
          ],
          "requester": {
            "id": [
              "entityID",
              3368970518
            ],
            "request": 95,
            "sequenceNumber": 0
          },
          "status": "rejected"
        }
      ]
    }
  ],
  "timeStamp": 11760
}

In [7]:
unnest_query = f"""
with srms as ({srm_query}),
extracted_srms as (select 
    json_extract_scalar(messagebody, '$.requestor.id[1]') as id,
    json_extract_scalar(messagebody, '$.requestor.type.role') as role,
    json_extract_scalar(messagebody, '$.requests[0].request.requestID') as requestid,
    json_extract_scalar(messagebody, '$.requests[0].request.requestType') as requesttype,
    json_extract_scalar(messagebody, '$.requests[0].request.id.id') as intersectionid,
    json_extract_scalar(messagebody, '$.requests[0].request.inBoundLane[1]') as inbound,
    json_extract_scalar(messagebody, '$.requests[0].request.outBoundLane[1]') as outbound,
    cast(json_extract_scalar(messagebody, '$.requestor.position.position.lat') as double) / 10000000 as lat,
    cast(json_extract_scalar(messagebody, '$.requestor.position.position.long') as double) / 10000000 as long,
    sourcedevice,
    timestamp,
    to_unixtime(from_iso8601_timestamp(timestamp)) as unixtime
from srms)

select timestamp, unixtime, lat, long, sourcedevice, id, intersectionid, requestid, requesttype, role, inbound, outbound from extracted_srms
"""

df = fetch_query_to_dataframe(cur, unnest_query)
df

,timestamp,unixtime,lat,long,sourcedevice,id,intersectionid,requestid,requesttype,role,inbound,outbound
0,2021-01-30T01:07:40.248Z,1.611969e+09,40.060616,-82.976402,morse_karl_cvcp,240217924,3412,81,priorityRequestUpdate,fire,52,122
1,2021-01-30T01:07:40.255Z,1.611969e+09,40.060616,-82.976402,morse_maize_cvcp,240217924,3412,81,priorityRequestUpdate,fire,52,122
2,2021-01-30T01:07:40.358Z,1.611969e+09,40.060617,-82.976431,morse_karl_cvcp,240217924,3412,81,priorityRequestUpdate,fire,52,122
3,2021-01-30T01:07:40.453Z,1.611969e+09,40.060618,-82.976461,morse_northlandridge_cvcp,240217924,3412,81,priorityRequestUpdate,fire,52,122
4,2021-01-30T01:07:40.455Z,1.611969e+09,40.060618,-82.976461,morse_karl_cvcp,240217924,3412,81,priorityRequestUpdate,fire,52,122
...,...,...,...,...,...,...,...,...,...,...,...,...
66652,2021-01-03T16:16:03.640Z,1.609691e+09,40.061481,-82.993456,morse_sandylane_cvcp,2605698581,3446,253,priorityRequestUpdate,fire,52,120
66653,2021-01-03T16:16:03.638Z,1.609691e+09,40.061481,-82.993456,morse_i71nb_cvcp,2605698581,3446,253,priorityRequestUpdate,fire,52,120
66654,2021-01-03T16:16:03.638Z,1.609691e+09,40.061481,-82.993456,morse_evanswood_cvcp,2605698581,3446,253,priorityRequestUpdate,fire,52,120
66655,2021-01-04T20:42:51.805Z,1.609793e+09,40.056974,-82.898664,morse_i270nb_cvcp,143189523,3163,3,priorityRequestUpdate,fire,115,18
66656,2021-01-04T12:32:23.430Z,1.609764e+09,40.057086,-82.910371,morse_stelzer_cvcp,1560218220,3228,3,priorityRequestUpdate,fire,83,22

In [8]:
df[df['id'] == '3073907835'].sort_values(by=['intersectionid', 'timestamp'])

,timestamp,unixtime,lat,long,sourcedevice,id,intersectionid,requestid,requesttype,role,inbound,outbound
8711,2021-01-22T12:17:11.357Z,1.611318e+09,39.846334,-82.937413,alumcreek_rohr_cvcp,3073907835,4622,20,priorityRequest,truck,18,85
22352,2021-01-22T12:17:11.618Z,1.611318e+09,39.846306,-82.937399,alumcreek_rohr_cvcp,3073907835,4622,20,priorityRequestUpdate,truck,18,85
33349,2021-01-22T12:17:27.227Z,1.611318e+09,39.844805,-82.936508,alumcreek_rohr_cvcp,3073907835,4622,21,priorityRequest,truck,19,52
28660,2021-01-22T12:17:27.315Z,1.611318e+09,39.844801,-82.936505,alumcreek_rohr_cvcp,3073907835,4622,21,priorityRequestUpdate,truck,19,52
19782,2021-01-22T12:17:27.402Z,1.611318e+09,39.844799,-82.936504,alumcreek_rohr_cvcp,3073907835,4622,21,priorityRequestUpdate,truck,19,52
...,...,...,...,...,...,...,...,...,...,...,...,...
31776,2021-01-22T12:16:44.705Z,1.611318e+09,39.850852,-82.938668,alumcreek_toy_cvcp,3073907835,4623,17,priorityRequestUpdate,truck,17,84
42247,2021-01-22T12:16:44.797Z,1.611318e+09,39.850830,-82.938666,alumcreek_toy_cvcp,3073907835,4623,17,priorityRequestUpdate,truck,17,84
31187,2021-01-22T12:16:44.991Z,1.611318e+09,39.850795,-82.938663,alumcreek_toy_cvcp,3073907835,4623,17,priorityRequestUpdate,truck,17,84
41346,2021-01-22T12:16:45.616Z,1.611318e+09,39.850679,-82.938653,alumcreek_toy_cvcp,3073907835,4623,17,priorityRequestUpdate,truck,17,84
32516,2021-01-22T12:16:50.817Z,1.611318e+09,39.849779,-82.938530,alumcreek_toy_cvcp,3073907835,4623,18,priorityRequestUpdate,truck,16,85

In [9]:
unnest_ssm_query = f"""
with ssms as ({ssm_query}),
extracted_ssms as (select 
    json_extract_scalar(messagebody, '$.status[0].sigStatus[0].requester.id[1]') as id,
    json_extract_scalar(messagebody, '$.status[0].sigStatus[0].requester.request') as requestid,
    json_extract_scalar(messagebody, '$.status[0].sigStatus[0].status') as status,
    json_extract_scalar(messagebody, '$.status[0].id.id') as intersectionid,
    timestamp,
    to_unixtime(from_iso8601_timestamp(timestamp)) as unixtime
from ssms),
status as (select min(timestamp) as timestamp, min(unixtime) as unixtime, status, id, intersectionid, requestid from extracted_ssms group by id, intersectionid, requestid, status),
granted_rejected_status as (select * from status where status = 'granted' or status = 'rejected'),
requested_status as (select * from status where status = 'requested'),
processing_status as (select * from status where status = 'processing')

select count(1) as count, array_agg((status, timestamp)) as lifecycle, max_by(status,timestamp) as final_status, id, intersectionid, requestid from status group by id, intersectionid, requestid
"""

"""
select 
    id, intersectionid, requestid, 
    granted_rejected_status.timestamp as time_granted_rejected,
    requested_status.timestamp as time_requested,
    processing_status.timestamp as time_processing
    
from granted_rejected_status 
left join requested_status using (id, intersectionid, requestid) 
left join processing_status using (id, intersectionid, requestid)
"""

df = fetch_query_to_dataframe(cur, unnest_ssm_query)
df

,count,lifecycle,final_status,id,intersectionid,requestid
0,2,"[[requested, 2021-01-23T04:37:49.193Z], [proce...",processing,909411921,3019,159
1,2,"[[processing, 2021-01-19T18:19:42.745Z], [requ...",processing,3731077896,4930,159
2,2,"[[processing, 2021-01-26T11:14:21.578Z], [requ...",processing,1447408107,3416,239
3,2,"[[processing, 2021-01-21T18:38:35.138Z], [requ...",processing,3040361013,3020,213
4,2,"[[requested, 2021-01-29T23:23:58.242Z], [proce...",processing,1847424534,4060,2
...,...,...,...,...,...,...
6054,2,"[[processing, 2021-01-16T03:55:05.849Z], [requ...",processing,3559024331,3024,1
6055,1,"[[rejected, 2021-01-01T06:56:12.140Z]]",rejected,2383056778,4006,139
6056,1,"[[rejected, 2021-01-29T14:03:15.041Z]]",rejected,1580317307,3020,121
6057,1,"[[rejected, 2021-01-30T00:11:57.242Z]]",rejected,1555692923,4060,130
6058,1,"[[rejected, 2021-01-20T14:54:06.598Z]]",rejected,3707945245,4036,2

In [10]:
df.describe(include='all')

,count,lifecycle,final_status,id,intersectionid,requestid
count,6059.000000,6059,6059,6059,6059,6059
unique,NaN,6059,4,2229,67,256
top,NaN,"[[requested, 2021-01-29T07:42:58.365Z], [proce...",processing,2891925512,4624,1
freq,NaN,1,2632,22,447,753
mean,1.472355,NaN,NaN,NaN,NaN,NaN
std,0.499276,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN
25%,1.000000,NaN,NaN,NaN,NaN,NaN
50%,1.000000,NaN,NaN,NaN,NaN,NaN
75%,2.000000,NaN,NaN,NaN,NaN,NaN
max,2.000000,NaN,NaN,NaN,NaN,NaN

In [11]:
df[df['count'] > 1]

,count,lifecycle,final_status,id,intersectionid,requestid
0,2,"[[requested, 2021-01-23T04:37:49.193Z], [proce...",processing,909411921,3019,159
1,2,"[[processing, 2021-01-19T18:19:42.745Z], [requ...",processing,3731077896,4930,159
2,2,"[[processing, 2021-01-26T11:14:21.578Z], [requ...",processing,1447408107,3416,239
3,2,"[[processing, 2021-01-21T18:38:35.138Z], [requ...",processing,3040361013,3020,213
4,2,"[[requested, 2021-01-29T23:23:58.242Z], [proce...",processing,1847424534,4060,2
...,...,...,...,...,...,...
6045,2,"[[requested, 2021-01-17T13:59:46.117Z], [proce...",processing,187347645,4040,199
6047,2,"[[requested, 2021-01-30T02:37:49.387Z], [grant...",granted,3400713913,3154,230
6049,2,"[[processing, 2021-01-21T00:14:06.267Z], [requ...",processing,3489180488,3017,1
6052,2,"[[granted, 2021-01-17T18:21:05.801Z], [request...",granted,565720848,3412,1
6054,2,"[[processing, 2021-01-16T03:55:05.849Z], [requ...",processing,3559024331,3024,1

In [12]:
df.sort_values(by=['id','intersectionid', 'requestid'])

,count,lifecycle,final_status,id,intersectionid,requestid
218,1,"[[rejected, 2021-01-26T17:55:11.551Z]]",rejected,1000225836,4620,20
2823,2,"[[requested, 2021-01-13T19:44:25.894Z], [proce...",processing,1002313426,3013,144
2184,2,"[[processing, 2021-01-13T19:44:41.493Z], [requ...",processing,1002313426,3013,145
5591,2,"[[requested, 2021-01-13T19:44:10.563Z], [proce...",processing,1002313426,3014,143
5157,2,"[[processing, 2021-01-06T23:14:55.050Z], [requ...",processing,1011627746,3024,198
...,...,...,...,...,...,...
5042,2,"[[processing, 2021-01-26T01:41:32.732Z], [requ...",processing,988948352,4040,1
4711,2,"[[processing, 2021-01-26T01:42:07.819Z], [requ...",processing,988948352,4042,2
1745,2,"[[requested, 2021-01-26T01:42:13.512Z], [proce...",processing,988948352,4043,3
3872,2,"[[requested, 2021-01-26T01:42:35.123Z], [proce...",processing,988948352,4045,252
640,2,"[[processing, 2021-01-18T19:16:18.464Z], [requ...",processing,989714638,3154,169

In [13]:
join_query = f"""
with parsed_ssms as ({unnest_ssm_query}), parsed_srms as ({unnest_query}),
matched as (
select 
    parsed_srms.id, parsed_srms.requestid, parsed_srms.intersectionid, final_status, lifecycle,
    role, requesttype, inbound, outbound, lat, long,
    parsed_srms.timestamp as srm_timestamp
from parsed_srms join parsed_ssms
on  parsed_srms.intersectionid = parsed_ssms.intersectionid 
and parsed_srms.id = parsed_ssms.id 
and parsed_srms.requestid = parsed_ssms.requestid)

select 
id,
requestid,
final_status,
lifecycle as status_lifecycle,
intersectionid,
role,
inbound,
outbound,
min(srm_timestamp) as initial_request_time,
array_agg((lat, long, srm_timestamp, requesttype)) as requests
from matched
group by id,
requestid,
final_status,
lifecycle,
intersectionid,
role,
inbound,
outbound
"""
print(join_query)
df = fetch_query_to_dataframe(cur, join_query)
df

with parsed_ssms as (
with ssms as (
select * from cve_signal_messages where os_partition = '2021_01' and messagetype = 'SSM'
),
extracted_ssms as (select
    json_extract_scalar(messagebody, '$.status[0].sigStatus[0].requester.id[1]') as id,
    json_extract_scalar(messagebody, '$.status[0].sigStatus[0].requester.request') as requestid,
    json_extract_scalar(messagebody, '$.status[0].sigStatus[0].status') as status,
    json_extract_scalar(messagebody, '$.status[0].id.id') as intersectionid,
    timestamp,
    to_unixtime(from_iso8601_timestamp(timestamp)) as unixtime
from ssms),
status as (select min(timestamp) as timestamp, min(unixtime) as unixtime, status, id, intersectionid, requestid from extracted_ssms group by id, intersectionid, requestid, status),
granted_rejected_status as (select * from status where status = 'granted' or status = 'rejected'),
requested_status as (select * from status where status = 'requested'),
processing_status as (select * from status where status = 'processing')

select count(1) as count, array_agg((status, timestamp)) as lifecycle, max_by(status,timestamp) as final_status, id, intersectionid, requestid from status group by id, intersectionid, requestid
), parsed_srms as (
with srms as (
select * from cve_signal_messages where os_partition = '2021_01' and messagetype = 'SRM'
),
extracted_srms as (select
    json_extract_scalar(messagebody, '$.requestor.id[1]') as id,
    json_extract_scalar(messagebody, '$.requestor.type.role') as role,
    json_extract_scalar(messagebody, '$.requests[0].request.requestID') as requestid,
    json_extract_scalar(messagebody, '$.requests[0].request.requestType') as requesttype,
    json_extract_scalar(messagebody, '$.requests[0].request.id.id') as intersectionid,
    json_extract_scalar(messagebody, '$.requests[0].request.inBoundLane[1]') as inbound,
    json_extract_scalar(messagebody, '$.requests[0].request.outBoundLane[1]') as outbound,
    cast(json_extract_scalar(messagebody, '$.requestor.position.position.lat') as double) / 10000000 as lat,
    cast(json_extract_scalar(messagebody, '$.requestor.position.position.long') as double) / 10000000 as long,
    sourcedevice,
    timestamp,
    to_unixtime(from_iso8601_timestamp(timestamp)) as unixtime
from srms)

select timestamp, unixtime, lat, long, sourcedevice, id, intersectionid, requestid, requesttype, role, inbound, outbound from extracted_srms
),
matched as (
select
    parsed_srms.id, parsed_srms.requestid, parsed_srms.intersectionid, final_status, lifecycle,
    role, requesttype, inbound, outbound, lat, long,
    parsed_srms.timestamp as srm_timestamp
from parsed_srms join parsed_ssms
on  parsed_srms.intersectionid = parsed_ssms.intersectionid
and parsed_srms.id = parsed_ssms.id
and parsed_srms.requestid = parsed_ssms.requestid)

select
id,
requestid,
final_status,
lifecycle as status_lifecycle,
intersectionid,
role,
inbound,
outbound,
min(srm_timestamp) as initial_request_time,
array_agg((lat, long, srm_timestamp, requesttype)) as requests
from matched
group by id,
requestid,
final_status,
lifecycle,
intersectionid,
role,
inbound,
outbound

,id,requestid,final_status,status_lifecycle,intersectionid,role,inbound,outbound,initial_request_time,requests
0,2983812622,116,processing,"[[requested, 2021-01-22T16:17:34.676Z], [proce...",3017,fire,18,83,2021-01-22T16:17:33.646Z,"[[40.005437, -82.9724542, 2021-01-22T16:17:34...."
1,3541667246,3,processing,"[[requested, 2021-01-15T20:56:10.000Z], [proce...",3408,fire,52,117,2021-01-15T20:56:09.958Z,"[[40.0615385, -82.9952684, 2021-01-15T20:56:11..."
2,1102624813,15,requested,"[[requested, 2021-01-28T14:56:07.212Z]]",4622,truck,81,22,2021-01-28T14:56:07.129Z,"[[39.8425724, -82.9350111, 2021-01-28T14:56:07..."
3,2465327259,9,requested,"[[requested, 2021-01-29T10:13:14.639Z]]",4620,truck,83,21,2021-01-29T10:13:14.303Z,"[[39.829559, -82.9338781, 2021-01-29T10:13:14...."
4,1446989783,2,rejected,"[[rejected, 2021-01-28T23:01:54.427Z]]",4624,truck,51,115,2021-01-28T23:01:54.366Z,"[[39.8522338, -82.9350746, 2021-01-28T23:01:54..."
...,...,...,...,...,...,...,...,...,...,...
5695,1491995086,11,rejected,"[[rejected, 2021-01-04T12:44:56.409Z]]",4622,truck,17,86,2021-01-04T12:44:56.398Z,"[[39.8463146, -82.9374626, 2021-01-04T12:44:56..."
5696,425210204,218,processing,"[[processing, 2021-01-06T15:02:47.383Z], [requ...",3013,fire,18,83,2021-01-06T15:02:45.342Z,"[[39.9957358, -82.979578, 2021-01-06T15:02:45...."
5697,4100110068,185,rejected,"[[rejected, 2021-01-06T02:22:22.089Z]]",4036,fire,49,117,2021-01-06T02:22:21.995Z,"[[40.0315905, -83.0143972, 2021-01-06T02:22:21..."
5698,3578904574,1,processing,"[[processing, 2021-01-12T04:25:33.274Z], [requ...",3228,fire,84,21,2021-01-12T04:25:31.193Z,"[[40.0553143, -82.9100218, 2021-01-12T04:25:31..."
5699,984937188,100,granted,"[[requested, 2021-01-30T20:02:45.687Z], [grant...",3154,transit,18,84,2021-01-30T20:02:45.675Z,"[[40.0331401, -82.9639257, 2021-01-30T20:02:45..."

In [14]:
df.describe(include='all')

,id,requestid,final_status,status_lifecycle,intersectionid,role,inbound,outbound,initial_request_time,requests
count,5700,5700,5700,5700,5700,5700,5700,5700,5700,5700
unique,2001,256,4,5521,67,4,26,39,5700,5700
top,2891925512,1,processing,"[[granted, 2021-01-30T01:08:26.743Z], [request...",4624,fire,82,20,2021-01-13T16:20:49.924Z,"[[40.0611878, -82.9863845, 2021-01-29T12:40:20..."
freq,22,680,2675,4,452,3412,900,577,1,1

In [15]:
df.sort_values(by=['intersectionid', 'id'])

,id,requestid,final_status,status_lifecycle,intersectionid,role,inbound,outbound,initial_request_time,requests
3286,1541063679,10,rejected,"[[requested, 2021-01-28T20:03:05.208Z], [rejec...",3010,transit,18,83,2021-01-28T20:03:05.125Z,"[[39.9838973, -82.9893802, 2021-01-28T20:03:05..."
3275,162979594,39,rejected,"[[rejected, 2021-01-30T13:27:16.548Z]]",3010,transit,82,19,2021-01-30T13:27:16.476Z,"[[39.9790975, -82.9897074, 2021-01-30T13:27:16..."
4246,1664105393,26,rejected,"[[rejected, 2021-01-30T00:00:03.848Z]]",3010,transit,82,19,2021-01-30T00:00:03.789Z,"[[39.9802866, -82.9895989, 2021-01-30T00:00:03..."
439,1860432118,50,rejected,"[[rejected, 2021-01-30T18:27:06.748Z]]",3010,transit,81,20,2021-01-30T18:27:06.726Z,"[[39.979109, -82.9896724, 2021-01-30T18:27:06...."
540,1860432118,51,rejected,"[[rejected, 2021-01-30T18:27:35.848Z]]",3010,transit,82,19,2021-01-30T18:27:35.790Z,"[[39.9815743, -82.9895048, 2021-01-30T18:27:35..."
...,...,...,...,...,...,...,...,...,...,...
1046,847755427,148,processing,"[[requested, 2021-01-17T20:55:38.546Z], [proce...",4930,fire,50,20,2021-01-17T20:55:38.483Z,"[[40.0378607, -82.9622574, 2021-01-17T20:55:38..."
5042,970586004,144,rejected,"[[rejected, 2021-01-29T20:24:55.853Z]]",4930,transit,18,52,2021-01-29T20:24:54.944Z,"[[40.0414753, -82.9608046, 2021-01-29T20:24:55..."
5562,970586004,144,rejected,"[[rejected, 2021-01-29T20:24:55.853Z]]",4930,transit,17,53,2021-01-29T20:25:24.660Z,"[[40.0407438, -82.9611284, 2021-01-29T20:25:24..."
4723,970790966,120,processing,"[[requested, 2021-01-09T19:42:58.704Z], [proce...",4930,fire,51,82,2021-01-09T19:42:58.618Z,"[[40.0401551, -82.9612902, 2021-01-09T19:42:58..."
3650,982389621,5,rejected,"[[rejected, 2021-01-29T10:43:36.252Z]]",4930,transit,17,53,2021-01-29T10:43:36.245Z,"[[40.0408067, -82.961123, 2021-01-29T10:44:06...."

In [16]:
df.to_csv('preemption_requests.csv', index=False)

In [17]:
unnest_query = f"""
with srms as (select * from smart_columbus_cve__captcha where os_partition = '2021_01' and messagetype = 'SRM'),
extracted_srms as (select 
    cast(json_extract(messagebody, '$.requests') as ARRAY<JSON>) as requests
from srms)

select cardinality(requests) from extracted_srms where cardinality(requests) > 1
"""

# df = fetch_query_to_dataframe(cur, unnest_query)
# df

In [18]:
status_query = f"""
with ssms as (select * from smart_columbus_cve__captcha where os_partition = '2021_01' and messagetype = 'SSM'),
extracted_ssms as (select 
    cast(json_extract(messagebody, '$.status') as ARRAY<JSON>) as statuses
from ssms)
select cardinality(statuses) from extracted_ssms where cardinality(statuses) > 1
"""

# df = fetch_query_to_dataframe(cur, status_query)
# df

In [19]:
status_query = f"""
with ssms as (select * from smart_columbus_cve__captcha where os_partition = '2021_01' and messagetype = 'SSM'),
extracted_ssms as (select 
    cast(json_extract(messagebody, '$.status[0].sigStatus') as ARRAY<JSON>) as statuses
from ssms)
select cardinality(statuses) from extracted_ssms where cardinality(statuses) > 1
"""

# df = fetch_query_to_dataframe(cur, status_query)
# df

In [20]:
# df[df['status'] == 'granted'].sort_values(by=['sourcedevice', 'ssm_timestamp'])

KeyError: 'status'

In [30]:
df['intersectionid'].unique()

array(['3017', '3408', '4622', '4620', '4624', '4065', '3012', '4060',
       '3162', '4026', '4625', '4044', '3412', '4035', '3013', '4621',
       '4040', '4037', '3010', '3093', '3154', '3414', '3159', '3023',
       '4042', '3417', '3440', '4623', '4027', '4043', '3446', '3015',
       '3407', '4006', '3024', '4045', '3405', '3019', '3020', '4028',
       '3409', '4007', '3228', '3018', '4055', '4032', '4036', '3014',
       '3415', '4070', '4038', '4033', '4072', '3413', '3416', '4025',
       '3021', '4930', '4627', '4009', '3410', '3237', '4034', '4107',
       '3092', '4021', '4029'], dtype=object)

In [28]:
df[df['final_status'] == 'granted']['intersectionid'].unique()

array(['3412', '3159', '3154', '3012', '4622'], dtype=object)

In [29]:
df[df['final_status'] == 'rejected']['intersectionid'].unique()

array(['4624', '4065', '4060', '4026', '4625', '4620', '3010', '3414',
       '3023', '4622', '3440', '4623', '4006', '3020', '4007', '3019',
       '3024', '4036', '3015', '3013', '4070', '3018', '3017', '4621',
       '4055', '4025', '4930', '3410', '3014', '3021', '4034', '4028',
       '4027', '3092', '4021', '3237', '4029'], dtype=object)

In [ ]:
one_vehicle = df[df['id'] == '502361261'].sort_values(by=['ssm_timestamp'])
one_vehicle

In [ ]:
import plotly.express as px

fig = px.scatter_mapbox(df, lat="lat", lon="long",     color="status",
                        hover_data=["id", "status", "requestid", "ssm_timestamp", "srm_timestamp", "intersectionid", "requesttype", "role"],
                  color_continuous_scale="delta", zoom=14.5)
fig.update_layout(mapbox_style="satellite", mapbox_accesstoken="pk.eyJ1Ijoic21ydGNidXMiLCJhIjoiY2ptMTB6YjIzMGVuazNwcWcyczk3a2ZmNSJ9.SjVhquTC7K5RzbGqoGZUYg")
fig.show()