In [1]:
import prestodb
import pandas as pd
conn=prestodb.dbapi.connect(
    host='localhost',
    port=9000,
    user='python',
    catalog='hive',
    schema='default',
)
cur = conn.cursor()

def fetch_query_to_dataframe(cur, query):
    cur.execute(query)
    rows = cur.fetchall()
    columns = list(map(lambda x: x[0], cur.description))
    return pd.DataFrame(rows, columns = columns)

In [2]:
rlr_query = f"""
select lane_red_light as red_light_run, bsm_timestamp as last_seen, id, sourcedevice, laneid, speed, lat, long
from smart_columbus_cve__cve_vehicles_in_lanes_with_state 
"""

cur.execute(rlr_query)
rows = cur.fetchall()

columns = list(map(lambda x: x[0], cur.description))

df = pd.DataFrame(rows, columns = columns)

pd.set_option('display.max_columns', None)
# df.to_csv('warning_data.csv', index=False)
df.describe()

               speed            lat           long
count  829565.000000  829565.000000  829565.000000
mean      455.235475      40.025089     -82.986769
std       230.545794       0.035056       0.032048
min         2.000000      39.837196     -83.020394
25%       270.000000      40.005883     -83.012347
50%       432.000000      40.026518     -82.998403
75%       615.000000      40.054851     -82.965004
max      1748.000000      40.062762     -82.890027

In [10]:
warn_query = f"""
with time_last_warned as (select min(bsm_timestamp) as first_warned, min_by(lat, bsm_timestamp) as lat, min_by(long, bsm_timestamp) as long, min_by(speed, bsm_timestamp) as speed, min_by(heading, bsm_timestamp) as heading, id, sourcedevice, laneid 
from smart_columbus_cve__cve_red_light_run_warning_issuance
where warning_issued = true
group by id, sourcedevice, laneid),

aggregated_records as (select bool_or(warning_issued) as warning_issued, max(bsm_timestamp) as last_seen, id, sourcedevice, laneid 
from smart_columbus_cve__cve_red_light_run_warning_issuance
group by id, sourcedevice, laneid)

select * from aggregated_records left outer join time_last_warned using (id, sourcedevice, laneid)
"""

df = fetch_query_to_dataframe(cur, warn_query)
df.describe()
df[df['warning_issued'] == True]

,id,sourcedevice,laneid,warning_issued,last_seen,first_warned,lat,long,speed,heading
53,3285795370,cleveland_24th_cvcp,81,True,2020-10-16T18:30:14.832Z,2020-10-16T18:30:14.113Z,40.006104,-82.971978,14.942759,24.9250
129,329333603,high_henderson_cvcp,17,True,2020-10-24T16:29:39.618Z,2020-10-24T16:29:39.517Z,40.051587,-83.020189,16.508617,182.9875
140,322808633,morse_indianola_cvcp,51,True,2020-10-18T18:54:10.809Z,2020-10-18T18:54:08.605Z,40.061722,-83.000336,40.085965,273.2750
160,3396572887,high_northbroadway_cvcp,51,True,2020-10-17T09:34:11.820Z,2020-10-17T09:34:09.619Z,40.031575,-83.015611,21.027236,90.8125
225,2652953143,high_lane_cvcp,51,True,2020-10-27T00:47:31.891Z,2020-10-27T00:47:24.296Z,40.006040,-83.008993,12.034737,81.6750
...,...,...,...,...,...,...,...,...,...,...
145440,1477197736,high_hudson_cvcp,81,True,2020-10-31T01:46:25.784Z,2020-10-31T01:46:25.671Z,40.014288,-83.011225,7.650335,349.1125
145444,936391027,high_henderson_cvcp,19,True,2020-10-25T01:38:44.070Z,2020-10-25T01:38:43.163Z,40.051568,-83.020098,13.018991,24.2625
145448,1486267241,morse_sinclair_cvcp,50,True,2020-10-20T17:36:03.288Z,2020-10-20T17:36:03.288Z,40.061655,-82.998057,62.410626,192.7750
145479,1898078908,morse_evanswood_cvcp,117,True,2020-10-29T18:50:36.363Z,2020-10-29T18:50:36.155Z,40.061469,-82.995095,30.869772,92.4750
145496,1785859629,morse_sinclair_cvcp,50,True,2020-10-26T16:18:25.431Z,2020-10-26T16:18:25.431Z,40.061661,-82.998033,69.345140,193.6625

In [4]:
test_query = f"""
with warn as ({warn_query})
select count(1) as instances, id, sourcedevice, laneid from warn group by id, sourcedevice, laneid
"""
df = fetch_query_to_dataframe(cur, test_query)

df.sort_values(by='instances')

        instances          id                sourcedevice laneid
0               1   299086198         high_henderson_cvcp     17
97016           1  3154196657        morse_sandylane_cvcp    115
97015           1  2898767266         cleveland_20th_cvcp     17
97014           1  2103157978              high_18th_cvcp     17
97013           1  3707224336       cleveland_hudson_cvcp     17
...           ...         ...                         ...    ...
48505           1  4286337204       cleveland_ferris_cvcp     17
48506           1  3548871065            high_hudson_cvcp     18
48507           1  3433083365  cleveland_westerville_cvcp     17
48501           1  4254667062      cleveland_windsor_cvcp     81
145511          1  3396980963         morse_sinclair_cvcp     50

[145512 rows x 4 columns]

In [11]:
join_query = f"""
with rlr as ({rlr_query}),
warn as ({warn_query})
select  id, 
        sourcedevice, 
        laneid, 
        red_light_run, 
        rlr.speed * 2.23694 / 50 as speed_at_cross_bar,
        rlr.lat as lat_at_cross_bar,
        rlr.long as long_at_cross_bar,
        warning_issued, 
        rlr.last_seen as rlr_report_last_seen, 
        warn.last_seen as warning_report_last_seen, 
        warn.first_warned as first_received_warning, 
        warn.lat as warning_lat, 
        warn.long as warning_long, 
        warn.speed as warning_speed, 
        heading as warning_heading 
    from rlr join warn using (id, sourcedevice, laneid)
"""

print(join_query)

df = fetch_query_to_dataframe(cur, join_query)
df.to_csv('warning_effectiveness.csv', index=False)
df

with rlr as (
select lane_red_light as red_light_run, bsm_timestamp as last_seen, id, sourcedevice, laneid, speed, lat, long
from smart_columbus_cve__cve_vehicles_in_lanes_with_state
),
warn as (
with time_last_warned as (select min(bsm_timestamp) as first_warned, min_by(lat, bsm_timestamp) as lat, min_by(long, bsm_timestamp) as long, min_by(speed, bsm_timestamp) as speed, min_by(heading, bsm_timestamp) as heading, id, sourcedevice, laneid
from smart_columbus_cve__cve_red_light_run_warning_issuance
where warning_issued = true
group by id, sourcedevice, laneid),

aggregated_records as (select bool_or(warning_issued) as warning_issued, max(bsm_timestamp) as last_seen, id, sourcedevice, laneid
from smart_columbus_cve__cve_red_light_run_warning_issuance
group by id, sourcedevice, laneid)

select * from aggregated_records left outer join time_last_warned using (id, sourcedevice, laneid)
)
select  id,
        sourcedevice,
        laneid,
        red_light_run,
        rlr.speed * 2.23694 / 50 as speed_at_cross_bar,
        rlr.lat as lat_at_cross_bar,
        rlr.long as long_at_cross_bar,
        warning_issued,
        rlr.last_seen as rlr_report_last_seen,
        warn.last_seen as warning_report_last_seen,
        warn.first_warned as first_received_warning,
        warn.lat as warning_lat,
        warn.long as warning_long,
        warn.speed as warning_speed,
        heading as warning_heading
    from rlr join warn using (id, sourcedevice, laneid)

,id,sourcedevice,laneid,red_light_run,speed_at_cross_bar,lat_at_cross_bar,long_at_cross_bar,warning_issued,rlr_report_last_seen,warning_report_last_seen,first_received_warning,warning_lat,warning_long,warning_speed,warning_heading
0,2426590948,morse_sandylane_cvcp,50,False,38.743801,40.061473,-82.992242,False,2020-10-24T14:07:40.858Z,2020-10-24T14:07:40.858Z,None,NaN,NaN,NaN,NaN
1,3106305337,high_18th_cvcp,82,False,24.158952,40.002311,-83.008490,False,2020-10-25T15:23:05.989Z,2020-10-25T15:23:05.989Z,None,NaN,NaN,NaN,NaN
2,629190121,cleveland_2nd_cvcp,82,False,22.011490,39.981657,-82.989495,False,2020-10-26T00:40:11.737Z,2020-10-26T00:40:11.737Z,None,NaN,NaN,NaN,NaN
3,4257103155,high_woodruff_cvcp,17,False,24.740556,40.003913,-83.008903,False,2020-10-29T16:44:24.989Z,2020-10-29T16:44:24.989Z,None,NaN,NaN,NaN,NaN
4,3344030496,high_torrence_cvcp,17,False,9.753058,40.035261,-83.016899,False,2020-10-25T21:57:46.457Z,2020-10-25T21:57:46.457Z,None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88100,957724122,high_morse_cvcp,19,False,24.293168,40.062741,-83.019493,False,2020-10-28T23:04:46.834Z,2020-10-28T23:04:46.834Z,None,NaN,NaN,NaN,NaN
88101,797937448,cleveland_huy_cvcp,49,True,1.744813,40.034906,-82.963461,False,2020-10-20T22:16:55.359Z,2020-10-20T22:16:54.453Z,None,NaN,NaN,NaN,NaN
88102,1713777487,cleveland_24th_cvcp,81,False,19.550856,40.006153,-82.971956,False,2020-10-19T15:18:56.754Z,2020-10-19T15:18:56.647Z,None,NaN,NaN,NaN,NaN
88103,75216433,cleveland_17th_cvcp,17,False,33.419884,40.000524,-82.975658,False,2020-10-19T19:15:56.375Z,2020-10-19T19:15:56.375Z,None,NaN,NaN,NaN,NaN
88104,1651587003,cleveland_innis_cvcp,17,False,37.267420,40.037640,-82.962474,False,2020-12-01T16:22:10.230Z,2020-10-28T17:08:30.537Z,None,NaN,NaN,NaN,NaN

In [12]:
df[df['warning_issued'] == True]

,id,sourcedevice,laneid,red_light_run,speed_at_cross_bar,lat_at_cross_bar,long_at_cross_bar,warning_issued,rlr_report_last_seen,warning_report_last_seen,first_received_warning,warning_lat,warning_long,warning_speed,warning_heading
36,1454956019,high_cooke_cvcp,49,True,7.650335,40.049653,-83.020036,True,2020-10-31T13:15:47.674Z,2020-10-31T13:15:47.674Z,2020-10-31T13:15:47.091Z,40.049649,-83.020011,9.484626,278.2250
40,523960787,high_henderson_cvcp,17,True,3.668582,40.051573,-83.020176,True,2020-10-28T01:52:07.336Z,2020-10-28T01:52:07.237Z,2020-10-28T01:52:07.132Z,40.051576,-83.020176,3.579104,184.0500
94,1362755118,high_11th_cvcp,50,True,13.153207,39.994817,-83.006795,True,2020-10-22T16:32:35.535Z,2020-10-22T16:32:35.535Z,2020-10-22T16:32:34.729Z,39.994808,-83.006737,14.405894,271.9625
97,1437959554,morse_stelzer_cvcp,17,True,20.087721,40.057909,-82.910554,True,2020-10-31T21:41:54.978Z,2020-10-31T21:41:54.978Z,2020-10-31T21:41:54.080Z,40.057980,-82.910545,19.058729,185.0875
112,1422515659,high_lane_cvcp,113,True,9.618842,40.005981,-83.009450,True,2020-10-21T10:09:57.295Z,2020-10-21T10:09:57.295Z,2020-10-21T10:09:56.694Z,40.005984,-83.009483,11.139961,91.2500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87975,557443076,high_olentangy_cvcp,82,True,20.982497,40.019481,-83.012601,True,2020-10-24T21:06:31.915Z,2020-10-24T21:06:31.915Z,2020-10-24T21:06:30.814Z,40.019390,-83.012577,20.714064,348.7125
88015,1543106858,morse_morsecrossing_cvcp,113,True,13.600595,40.057795,-82.918515,True,2020-10-26T16:10:33.276Z,2020-10-26T16:10:33.276Z,2020-10-26T16:10:32.276Z,40.057812,-82.918590,16.732311,97.0375
88020,27686473,high_morse_cvcp,49,True,17.627087,40.062489,-83.019186,True,2020-10-30T17:14:57.484Z,2020-10-30T17:14:57.383Z,2020-10-30T17:14:56.399Z,40.062486,-83.019082,18.835035,272.3875
88055,1359135520,morse_westerville_cvcp,117,True,33.375145,40.058802,-82.937864,True,2020-10-23T20:54:47.072Z,2020-10-23T20:54:46.969Z,2020-10-23T20:54:46.645Z,40.058805,-82.937933,32.972496,93.1875
88072,2206164955,cleveland_5th_cvcp,17,True,6.442387,39.986641,-82.989091,True,2020-10-16T19:17:54.385Z,2020-10-16T19:17:54.385Z,2020-10-16T19:17:53.784Z,39.986660,-82.989077,10.513618,209.6625

In [6]:
validation_query = f"""
with eff as ({join_query})
select count(1) as instances, id, sourcedevice, laneid from eff group by id, sourcedevice, laneid
"""
df = fetch_query_to_dataframe(cur, validation_query)

df.describe()

          instances
count  84147.000000
mean       1.047037
std        0.394201
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max       89.000000

In [7]:
agg_query = f"""
with warning_effectiveness as ({join_query})
select count(1) as count, red_light_run, warning_issued from warning_effectiveness group by red_light_run, warning_issued
"""

fetch_query_to_dataframe(cur, agg_query)

   count  red_light_run  warning_issued
0  84753          False           False
1    581          False            True
2   1230           True           False
3   1541           True            True

In [8]:
report_query = f"""
with 
    warning_effectiveness as ({join_query}),
    red_light as (select count(1) as red_light_runs, sourcedevice from warning_effectiveness where red_light_run = true group by sourcedevice),
    warnings as (select count(1) as warnings_issued, sourcedevice from warning_effectiveness where warning_issued = true group by sourcedevice),
    totals as (select count(1) as total_vehicles, sourcedevice from warning_effectiveness group by sourcedevice)
    select * from red_light join warnings using (sourcedevice) join totals using (sourcedevice)
"""

fetch_query_to_dataframe(cur, report_query)

,sourcedevice,red_light_runs,warnings_issued,total_vehicles
0,high_northwood_cvcp,26,27,2314
1,high_arcadia_cvcp,39,38,1582
2,high_11th_cvcp,107,55,1772
3,morse_sunbury_cvcp,14,12,475
4,morse_sinclair_cvcp,60,44,1533
...,...,...,...,...
60,high_oaklandpark_cvcp,10,15,1558
61,morse_morsecrossing_cvcp,63,40,653
62,high_lane_cvcp,356,146,3761
63,morse_northlandridge_cvcp,8,3,604
64,cleveland_westerville_cvcp,22,29,1668

In [9]:
df.plot.pie(subplots=True, figsize=(11, 6), y='count', x='warning_issued')

KeyError: 'count'

In [ ]:
vehicle_query = f"""
with bsm_subset as (
    SELECT cast(json_extract_scalar(messagebody, '$.coreData.lat') as double) / 10000000 as long, 
           cast(json_extract_scalar(messagebody, '$.coreData.long') as double) / 10000000 as lat,
           json_extract_scalar(messagebody, '$.coreData.id') as id,
           timestamp,
           sourcedevice
           FROM smart_columbus_cve__captcha where os_partition = '2021_01'
    and messagetype = 'BSM' 
    and day(from_iso8601_timestamp(timestamp)) = 5
    --and json_extract_scalar(messagebody, '$.coreData.id') = '3773743816'
    --and sourcedevice = 'high_hudson_cvcp'
    order by timestamp asc
),

aggregated_pos as (
    select array_agg((lat, long, 0, to_unixtime(from_iso8601_timestamp(timestamp)))), id, sourcedevice from bsm_subset group by id, sourcedevice
)

select * from aggregated_pos
"""

cur.execute(vehicle_query)
rows = cur.fetchall()

columns = list(map(lambda x: x[0], cur.description))

df = pd.DataFrame(rows, columns = columns)

df.to_csv('vehicle_trip.csv', index=False)
df

In [ ]:
path_df = pd.read_csv('vehicle_trip.csv')

import geojson
from geojson import LineString, Feature, FeatureCollection
import json

# LineString()

cars = path_df['_col0'].to_list()
features = []

for car in cars:
    points = json.loads(car)
    path_feature = Feature(geometry=LineString(points[0::10]))
    features.append(path_feature)

geo = geojson.dumps(FeatureCollection(features))

with open('path.geojson', 'w') as f:
    f.write(geo)

In [ ]:
import plotly.express as px

rlr_query = f"""
select 
    min_by(timestamp, distance) as timestamp, 
    min_by(lat, distance) as lat,
    min_by(long, distance) as long,
    min_by(speed, distance) as speed,
    min_by(heading, distance) as heading,
    id, laneid, sourcedevice 
from cve_bsm_python_scratch group by id, laneid, sourcedevice
"""

df = fetch_query_to_dataframe(cur, rlr_query)
df.describe()

In [ ]:
fig = px.scatter_mapbox(df, lat="lat", lon="long",     color="laneid",
                        hover_data=["id", "speed", "heading", "timestamp"],
                  color_continuous_scale=px.colors.cyclical.IceFire, zoom=14.5)
fig.update_layout(mapbox_style="satellite", mapbox_accesstoken="pk.eyJ1Ijoic21ydGNidXMiLCJhIjoiY2ptMTB6YjIzMGVuazNwcWcyczk3a2ZmNSJ9.SjVhquTC7K5RzbGqoGZUYg")
fig.show()